---
- name: "Dnf module disable -y mariadb # prevent the default module stream from being used"
  ansible.builtin.command: dnf module disable -y mariadb
  register: repo_mariadb__command_result
  changed_when: "'Nothing to do' not in repo_mariadb__command_result.stdout"
  tags:
    - repo_mariadb
