---
sshd__ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
sshd__kex: curve25519-sha256@libssh.org
sshd__macs: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
sshd__password_authentication: false
sshd__permit_root_login: "yes"
sshd__port: 22
sshd__service_enabled: true
sshd__service_state: started
sshd__use_dns: false

sshd__log_level__dependent_var: ""
sshd__log_level__group_var: ""
sshd__log_level__host_var: ""
sshd__log_level__role_var: INFO
sshd__log_level__combined_var: "{{ sshd__log_level__host_var if (sshd__log_level__host_var | string | length) else sshd__log_level__group_var if (sshd__log_level__group_var
  | string | length) else sshd__log_level__dependent_var if (sshd__log_level__dependent_var | string | length) else sshd__log_level__role_var }}"
