---
redis__service_enabled: true
redis__service_limit_nofile: 10240
redis__service_timeout_start_sec: 90s
redis__service_timeout_stop_sec: 90s

# -----------------------------------------------------------------------------

redis__kernel_settings__sysctl__dependent_var:
  # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition.
  # To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run
  # the command 'sysctl vm.overcommit_memory=1' for this to take effect.
  - name: vm.overcommit_memory
    value: 1
  # WARNING: The TCP backlog setting of 511 cannot be enforced because
  # /proc/sys/net/core/somaxconn is set to the lower value of 128.
  - name: net.core.somaxconn
    value: 1024
redis__kernel_settings__transparent_hugepages__dependent_var: madvise
