---
rocketchat__application_path: /opt/Rocket.Chat

rocketchat__mongodb_host: localhost
rocketchat__mongodb_port: 27017
rocketchat__mongodb_repl_set_name: rs01

rocketchat__port: 3000
rocketchat__service_enabled: true
rocketchat__service_state: started

rocketchat__version: latest

# -----------------------------------------------------------------------------

rocketchat__apps__apps__dependent_var:
  - name: git
    state: present

rocketchat__mongodb__conf_replication_repl_set_name__dependent_var: "{{ rocketchat__mongodb_repl_set_name }}"
