---
- name: "Icingadb: restart icinga2"
  ansible.builtin.service:
    name: icinga2
    state: restarted

- name: "Icingadb: restart icingadb"
  ansible.builtin.service:
    name: icingadb
    state: restarted
