---
influxdb__conf_continuous_queries_log_enabled: false
influxdb__conf_continuous_queries_run_interval: 1s
influxdb__conf_log_queries_after: "0s"
influxdb__conf_logging_level: warn
influxdb__databases__dependent_var: []
influxdb__databases__group_var: []
influxdb__databases__host_var: []
influxdb__databases__role_var: []
influxdb__databases__combined_var: "{{ influxdb__databases__role_var + influxdb__databases__group_var + influxdb__databases__host_var + influxdb__databases__dependent_var
  | flatten }}"
influxdb__dump_timer_enabled: true
influxdb__users__dependent_var: []
influxdb__users__group_var: []
influxdb__users__host_var: []
influxdb__users__role_var: []
influxdb__users__combined_var: "{{ influxdb__users__role_var + influxdb__users__group_var + influxdb__users__host_var + influxdb__users__dependent_var | flatten }}"

influxdb__service_enabled: true

# -----------------------------------------------------------------------------

influxdb__python_venv__venvs__dependent_var:
  - name: influxdb
    packages:
      - influxdb
      - requests
