---
- name: Install and configure Grafana
  hosts:
    - lfops_grafana

  roles:
    - role: linuxfabrik.lfops.repo_grafana
      when:
        - not grafana_server__skip_repo_grafana | d(false)

    - role: linuxfabrik.lfops.grafana
