---
- name: Install and configure a KVM host
  hosts:
    - lfops_kvm_host

  roles:
    - role: linuxfabrik.lfops.python
      python__modules__dependent_var: "{{ kvm_host__python__modules__dependent_var | d([]) }}"
      when:
        - not kvm_host__skip_python | d(false)

    - role: linuxfabrik.lfops.kvm_host
