---
- name: Install Opensearch on the system
  hosts:
    - lfops_opensearch

  roles:
    - role: linuxfabrik.lfops.repo_opensearch
      when:
        - not opensearch__skip_repo_opensearch | default(false)

    - role: linuxfabrik.lfops.opensearch
