---
- name: Manage and configure the Remi Repository
  hosts:
    - lfops_repo_remi

  roles:
    - role: linuxfabrik.lfops.yum_utils
      when:
        - ansible_facts["os_family"] == "RedHat"

    - role: linuxfabrik.lfops.repo_epel
      when:
        - ansible_facts["os_family"] == "RedHat"
        - ansible_facts["distribution_major_version"] in ["7", "8"]

    - role: linuxfabrik.lfops.repo_remi
