---
- name: The Linuxfabrik basic setup
  hosts:
    - lfops_setup_basic

  pre_tasks:
    # currently, this is thought for centos7, rocky8 and fedora35. therefore, if there is no when-staement, it should work against those.
    # please extend and improve as required.

    - name: Check if the OS is supported
      ansible.builtin.meta: end_host
      when:
        - ansible_facts["os_family"] != "RedHat"
      tags:
        - always

  roles:
