---
- name: Configure sshd
  hosts:
    - lfops_sshd

  roles:
    - role: linuxfabrik.lfops.policycoreutils
      when:
        - ansible_facts["os_family"] == "RedHat"

    - role: linuxfabrik.lfops.sshd
